import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex items-center justify-center bg-brand-light-2">
        <main className="w-full max-w-3xl mx-auto p-6">
          {children}
        </main>
      </body>
    </html>
  )
}
